[package]
name = "neiru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
target = "aarch64-unknown-linux-gnu"

[dependencies]
derivative = "2.2.0"